### PR TITLE
Slackord v4.0 RC1

### PR DESCRIPTION
**Pull request by thomasloupe**
NEW - Slackord now uses the channels.json file to get channel descriptions and will recreate channels with the descriptions.
NEW - Slackord will now check if a message was pinned in Slack, and will pin it in Discord as well.
NEW - Slackord now supports _most_ markdown language, including code blocks, masked links, italics, underline, numbered and bulleted lists, and more.
NEW - Slackord now defaults to the user's local clock to generate timestamps for messages.
NEW - Slackord will now use the first 20 characters of a thread start message to name the thread.
NEW - Slackord now deconstructs messages from Slack json exports instead of reading the JSON.
NEW - Slackord now reconstructs Slack messages into Discord compatible message objects.
NEW - Slackord now parses the users.json file and uses the first non-null or empty value for a user's message username in order of `display_name` > `user_name` > `real_name`.
NEW - Slackord has been updated to .NET 8 RC1.
FIX - Empty threads, and threads out of sync.
FIX - Bug that could cause message splits to break markdown if the split happened on a markdown.
FIX - Multiple potential thread locks in parsing, deconstruction and reconstruction.
FIX - Multiple bugs with the progress bar that could cause it not to progress properly.
CHANGE - Instead of having a delay in creating Discord channels, Slackord now has no delay and channels much faster (rate-limiting backoff still applies).
CHANGE - Multiple log and exception strings to be more verbose.
CHANGE - [Developers] - Refactored the entirety of the Slackord project. Classes are better broken up based on their purpose. code is more straightforward, and comments will continue to be added to sections of code to assist developers and users.
CHANGE - In previous versions of Slackord, channels.json and users.json files were not needed. In an approach to use data that's already available, Slackord now utilizes both files to map users, channels, and channel descriptions correctly.

NOTE TO DEVELOPERS - If you're looking to work on your own fork of Slackord, .NET 8 RC1 and Visual Studio 2022 Preview 17.8 is required as 17.6 is the lowest version .NET 8 supports.

Are you a .NET/MAUI developer? Slackord is looking for contributors. Join the Slackord Discord and show your interest in helping!

### CODE REVIEW

**Comment by alexghi** [comment]
Where can I find the v4 binary for mac? Do i have to build it from source?

**Comment by thomasloupe** [comment]
The mac version won't connect to Discord and isn't available until I can sort out why. Could definitely use some help! If you're .NET/C#/MAUI experienced, would love to speak to you in Discord!

**Comment by alexghi** [comment]
at the moment I tried it on a windows machine but I'm getting this `Error encountered while creating slash command: Value cannot be null. (Parameter 'Description')` at the very last of the steps needed to import into a channel
Do you have any leads what might cause this error? I checked the source code and it seems to happen somwhere in ```Task ClientReady()```

**Comment by thomasloupe** [comment]
You are posting questions in a Pull Request.
I would suggest visiting our Discord or posting an issue. Discord is preferred, then I can have a look.

**Pull request merged**
